#!/usr/bin/env bash

# handcoded with 🤍 by 𝙆𝙊𝘿𝞝𝙋𝞸𝞝𝙏 <iam@kodepoet.dev>

export ENV_FILE="bootstrap.env"

set -aeuo pipefail nounset

gum style \
  --border normal \
  --margin "1" \
  --padding "1 2" \
  --border-foreground 212 \
  "docker secrets buildkit security $(gum style --foreground 212 'FLUENT').";

source ./sekrets

for key in "${!SEKRETS[@]}";
do
  op run --no-masking --env-file="$ENV_FILE" -- \
    echo "$(printenv "${SEKRETS[$key]}")" | docker secret create \
      --label env=$APP_ENV \
      --label app=fluent \
      --label rev=1 \
      "${key}" - || :
done
