#!/bin/bash

# handcoded with 🤍 by 𝙆𝙊𝘿𝞝𝙋𝞸𝞝𝙏 <iam@kodepoet.dev>

set -aeuo pipefail nounset

source ./sekrets;

for key in "${!SEKRETS[@]}";
do
  if [ -f /run/secrets/"${key}" ]; then
    envpath="/run/secrets/${key}"
    val=$(cat "$envpath")
    export "${SEKRETS[$key]}"="$val";
    export "${SEKRETS[$key]}_FILE"="$envpath";
    echo "Exporting secret -> ${SEKRETS[$key]}"
  fi
done
